services:
  db:
    image: postgres:14
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: ./mini_mockapi
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    working_dir: /app
    command: /bin/sh -c "npx prisma migrate deploy && npm run build && npm run start"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
